## Classificate random numbers between 0 to 1, which are more than 0.5 or not.

In [1]:
# Create training data and lables

import numpy as np
data = np.random.random (10000)                  # 10,000 number automatically between 0 to 1         # these are our training data
#data.shape                                      # output: 10000                                      # How many dimensions does it have.
# This is not suitable output for our model. So we need 2 dimension
data.shape = 10000,1                             # 10,000 number and 1 value per observation
data.shape

(10000, 1)

In [2]:
data

array([[0.62802451],
       [0.47025878],
       [0.31748108],
       ...,
       [0.67010541],
       [0.78227413],
       [0.10342687]])

In [3]:
# Larger than 0.5 --> class true
# Smaller than 0.5 --> class false

labels = np.array(data >= 0.5)                   # It create array in in boolean.
labels                                           # This is not suitable output for us. because we need value.

array([[ True],
       [False],
       [False],
       ...,
       [ True],
       [ True],
       [False]])

In [4]:
# Larger than 0.5 --> class 1
# Smaller than 0.5 --> class 0

labels = np.array(data >= 0.5 , dtype=int)
labels

array([[1],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]])

In [5]:
# Build the Model
from keras import Sequential
from keras.layers import Dense

model = Sequential([
       Dense( units=8, input_shape=(1,), activation='relu'),
       Dense( units=2 , activation='softmax' )
  ])

model.summary()
#parameters: 16 ---> input neuron to the hidden neurons: 8 + each neuron has bias: 8
#parameters: 18 ---> hidden neurons to the output neurons: 16 + each output neurons has bias: 2

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 16        
                                                                 
 dense_1 (Dense)             (None, 2)                 18        
                                                                 
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [6]:
# Compile the model: model ready for training
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)  # optimizer= It changes the weights and the bias parameters of the model during learning


In [7]:
# Train the model
model.fit(
    x=data,
    y=labels,
    epochs=10,
    verbose=2
)

Epoch 1/10
313/313 - 4s - loss: 0.6216 - accuracy: 0.6376 - 4s/epoch - 12ms/step
Epoch 2/10
313/313 - 0s - loss: 0.4555 - accuracy: 0.8681 - 339ms/epoch - 1ms/step
Epoch 3/10
313/313 - 0s - loss: 0.3265 - accuracy: 0.9386 - 350ms/epoch - 1ms/step
Epoch 4/10
313/313 - 0s - loss: 0.2373 - accuracy: 0.9727 - 340ms/epoch - 1ms/step
Epoch 5/10
313/313 - 0s - loss: 0.1772 - accuracy: 0.9868 - 344ms/epoch - 1ms/step
Epoch 6/10
313/313 - 0s - loss: 0.1390 - accuracy: 0.9925 - 351ms/epoch - 1ms/step
Epoch 7/10
313/313 - 0s - loss: 0.1147 - accuracy: 0.9951 - 332ms/epoch - 1ms/step
Epoch 8/10
313/313 - 0s - loss: 0.0982 - accuracy: 0.9944 - 304ms/epoch - 972us/step
Epoch 9/10
313/313 - 0s - loss: 0.0864 - accuracy: 0.9952 - 316ms/epoch - 1ms/step
Epoch 10/10
313/313 - 0s - loss: 0.0774 - accuracy: 0.9961 - 357ms/epoch - 1ms/step


In [8]:
# Testing the model
test_data = np.array([0, 0.2, 0.4, 0.6, 0.8, 1])
predictions = model.predict(test_data)
predictions                            #Output: [activation of the first output neuron, activation of the second output neuron]

1/1 [==============================] - 0s 124ms/step


array([[9.9263787e-01, 7.3620854e-03],
       [9.9229676e-01, 7.7032177e-03],
       [9.0392137e-01, 9.6078627e-02],
       [9.7541116e-02, 9.0245891e-01],
       [1.2401593e-03, 9.9875987e-01],
       [1.4264839e-05, 9.9998569e-01]], dtype=float32)

In [9]:
# Now we want to know which of the 2 output neurons was most active
print(np.argmax(predictions, axis=1))

[0 0 0 1 1 1]


In [10]:
# Validating the model during training
model.fit(
    x = data,
    y = labels,
    epochs=10,
    verbose=1,
    validation_split=0.1                       #the model will take the last 10% of the training data

)

Epoch 1/10
282/282 [==============================] - 1s 2ms/step - loss: 0.0713 - accuracy: 0.9972 - val_loss: 0.0645 - val_accuracy: 0.9950
Epoch 2/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0662 - accuracy: 0.9981 - val_loss: 0.0577 - val_accuracy: 0.9980
Epoch 3/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0619 - accuracy: 0.9978 - val_loss: 0.0535 - val_accuracy: 0.9960
Epoch 4/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0581 - accuracy: 0.9974 - val_loss: 0.0513 - val_accuracy: 1.0000
Epoch 5/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0548 - accuracy: 0.9982 - val_loss: 0.0469 - val_accuracy: 0.9940
Epoch 6/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0521 - accuracy: 0.9982 - val_loss: 0.0447 - val_accuracy: 0.9980
Epoch 7/10
282/282 [==============================] - 0s 2ms/step - loss: 0.0496 - accuracy: 0.9974 - val_loss: 0.0440 - val_accuracy: 0.9980
Epoch 